apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-component-parent-oulr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-imqv-tenant/build-suite-component-update-kkrx/multi-component-parent-oulr@sha256:74297242a34c0a5c6cfd600f593b0693bb58588f6cfbf32bad60af65602eb5a7
        name: container-image
        resources: {}
status: {}
